# Generated by Django 4.2.7 on 2023-11-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_active',
            field=models.BooleanField(default=False, verbose_name='Верификация по почте'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Признак активности'),
        ),
    ]
