# Generated by Django 4.2.7 on 2023-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_email_active_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_active',
        ),
        migrations.AddField(
            model_name='user',
            name='code_for_verify',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код для верификации почты'),
        ),
    ]
