# Generated by Django 4.2.7 on 2023-11-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_email_active_user_code_for_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active_status', 'Can_active_user')]},
        ),
    ]
