# Generated by Django 4.2.7 on 2023-11-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_client_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing', models.DateTimeField(auto_now=True, verbose_name='Время отправления')),
                ('period', models.CharField(max_length=100, verbose_name='Периодичность')),
                ('status_of_mailing', models.CharField(max_length=100, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='newsletter.client', verbose_name='Клиент для рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.message', verbose_name='Текст рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
