# Generated by Django 4.2.7 on 2023-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('OD', 'Раз в день'), ('OW', 'Раз в неделю'), ('OM', 'Раз в месяц')], max_length=100, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status_of_mailing',
            field=models.CharField(choices=[('COM', 'Завершена'), ('CRE', 'Создана'), ('LAU', 'Запущена')], max_length=100, verbose_name='Статус'),
        ),
    ]
