# Generated by Django 4.2.7 on 2023-11-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_newsletter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time_mailing',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
    ]
