# Generated by Django 4.2.7 on 2023-11-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_newsletter_time_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_last_mailing', models.DateTimeField(auto_now=True, verbose_name='Дата и время последней рассылки')),
                ('result_mailing', models.CharField(max_length=50, verbose_name='результат попытки')),
                ('answer_mailing_service', models.CharField(max_length=255, verbose_name='Ответ почтового сервиса')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Набор логов',
                'verbose_name_plural': 'Наборы логов',
            },
        ),
    ]
