# Generated by Django 4.2.7 on 2023-11-17 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_mailinglogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='end_of_mailing',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 16, 8, 46, 497114, tzinfo=datetime.timezone.utc), verbose_name='Дата и время окончание рассылки'),
        ),
    ]
