# Generated by Django 4.2.7 on 2023-11-18 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_newsletter_end_of_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='end_of_mailing',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 4, 26, 27, 220783, tzinfo=datetime.timezone.utc), verbose_name='Дата и время окончание рассылки'),
        ),
    ]
