# Generated by Django 4.2.7 on 2023-11-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_newsletter_end_of_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='end_of_mailing',
            field=models.DateTimeField(default='01-01-2024 12:00', verbose_name='Дата и время окончание рассылки'),
        ),
    ]
