# Generated by Django 4.2.7 on 2023-11-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_alter_newsletter_end_of_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status_of_mailing',
            field=models.CharField(choices=[('COMPLETE', 'Завершена'), ('CREATED', 'Создана'), ('LAUNCHED', 'Запущена')], max_length=100, verbose_name='Статус'),
        ),
    ]
