# Generated by Django 4.2.7 on 2023-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_alter_newsletter_status_of_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('ONCE_DAY', 'Раз в день'), ('ONCE_WEEK', 'Раз в неделю'), ('ONCE_MONT', 'Раз в месяц')], max_length=100, verbose_name='Периодичность'),
        ),
    ]
