# Generated by Django 4.2.7 on 2023-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_newsletter_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='time_mailing',
        ),
    ]
