# Generated by Django 4.2.7 on 2023-11-18 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_remove_newsletter_time_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='time_mailing',
            field=models.TimeField(default=datetime.datetime(2023, 11, 18, 8, 55, 31, 458339, tzinfo=datetime.timezone.utc), verbose_name='Время рассылки'),
        ),
    ]
