# Generated by Django 4.2.7 on 2023-11-18 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_alter_newsletter_end_of_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time_mailing',
            field=models.TimeField(default=datetime.datetime(2023, 11, 18, 9, 4, 33, 400048), verbose_name='Время рассылки'),
        ),
    ]
