# Generated by Django 4.2.7 on 2023-11-21 00:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0023_alter_newsletter_time_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='time_mailing',
            field=models.TimeField(default=datetime.datetime(2023, 11, 21, 0, 35, 21, 568149), verbose_name='Время рассылки'),
        ),
    ]
