# Generated by Django 4.2.7 on 2023-11-21 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0024_newsletter_creator_alter_newsletter_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time_mailing',
            field=models.TimeField(default=datetime.datetime(2023, 11, 21, 1, 25, 42, 594056), verbose_name='Время рассылки'),
        ),
    ]
