# Generated by Django 4.2.7 on 2023-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('article_content', models.TextField(verbose_name='Содержимое статьи')),
                ('image', models.ImageField(upload_to='blog_preview/', verbose_name='Изображение')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
