# Generated by Django 4.2.7 on 2023-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_preview/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
